# Numpy 

## 1단계

In [ ]:
# 1. 불러오기
import numpy as np

In [ ]:
# 2. 배열 만들기 
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# 2. 배열 차원 변경
b = a.reshape(3,5) #행,열
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b = a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 3. 배열 정보 확인하기 
a.shape

(15,)

In [ ]:
a.shape

In [ ]:
b.shape

(3, 5)

In [ ]:
b.shape

(3, 5)

In [ ]:
### 연습 
### 0~9까지 배열을 만들어 보세요. 
### 0~9까지 배열을 2행 5열로 차원을 변경해 보세요. 
### 0~9까지 숫자로 만든 2행 5열 정보를 확인해 보세요.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 2단계

In [ ]:
# 1. 인덱싱

# 배열 만들기
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# 두 번째 원소 인덱싱하기
a[1]

1

In [ ]:
# 네 번째 원소 인덱싱하기
a[3]

3

In [ ]:
a[2]

2

In [ ]:
# 2. 슬라이싱

a[0:2] 
# 0이상 2 미만 

array([0, 1])

In [ ]:
a[0:2]

array([0, 1])

In [ ]:
a[5:]
# 5 이상부터 끝까지

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[:4]
# 처음부터 4 미만

array([0, 1, 2, 3])

In [ ]:
a[:4]

array([0, 1, 2, 3])

In [ ]:
### 연습
### a의 배열의 3 이상 6 미만 슬라이싱 해보세요.

In [ ]:
a[3:6]

array([3, 4, 5])

# 3단계

In [ ]:
# 1. 사칙연산 

## 1.1 배열 만들기
a = np.array([
[1,2,3],
[4,5,6]
], dtype = np.float64)

b = np.array([
[7,8,9],
[10,11,12]
], dtype = np.float64)

In [ ]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
b

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
## 1.2 사칙연산 하기
print(a+b)

[[ 8. 10. 12.]
 [14. 16. 18.]]


In [ ]:
print(a-b)

[[-6. -6. -6.]
 [-6. -6. -6.]]


In [ ]:
print(a*b)

[[ 7. 16. 27.]
 [40. 55. 72.]]


In [ ]:
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
### 연습
### 아래의 배열로 사칙연산을 해보세요.

a = np.array([
[1000,1000,1000],
[1000,1000,1000]
], dtype = np.float64)

b = np.array([
[4,4,4],
[4,4,4]
], dtype = np.float64)


In [ ]:
print(a+b)

[[1004. 1004. 1004.]
 [1004. 1004. 1004.]]
